### ISSUE TITLE
Warum gibt es noch keine Testversion im GitHub?

### ISSUE THREAD

**Issue by mrentsch65** [TINF20C/Team_3_OMLOX_als_PC-Dienst#14]
Hier ist nur ein leeres Verzeichnis:
![image](https://user-images.githubusercontent.com/50681355/163755941-5ad2b420-77ca-41d4-8077-0048368c07ef.png)

**Comment by samirahmetovic** [comment]
Die Testversion ist im dev Branch.
Mit den Tests von Aaron Kurpries werden finalen Änderungen an der Software gemacht.
Danach wird der neue Sourcecode, mit der executable und einem github release 1.0 veröffentlicht
