### ISSUE TITLE
SRS: GUI-Entwurf fehlt vollständig

### ISSUE THREAD

**Issue by mrentsch65** [TINF20C/Team_3_OMLOX_als_PC-Dienst#4]
Bitte asap nachziehen. Woher soll der Kunde sonst eine Vorstellung davon bekommen, was da entwicklet werden soll...
Tip: Mittels Erstellung des Usermanuals gleich am Anfang im Rahmen der Anforderungsanalyse (SRS) könnte übrigens sehr gut das GUI-Design und die Usability des neuen Tools hergeleitet werden!

**Comment by juliabb1** [comment]
Im SRS nun zu finden
